title: Cocoon
url: "https://pro-panda.tech"
baseurl: "/cocoon"

markdown: kramdown

tracking_id: #

footer_url: "https://github.com/pro-panda"
footer_text: "Pro-Panda | 2018"

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

nav:
 - name: "About"
   link: "/about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
