title: Cocoon
url: "https://pro-panda.tech"
baseurl: "/cocoon"

markdown: kramdown

tracking_id: #

footer_url: "https://github.com/pro-panda"
footer_text: "Pro-Panda | 2018"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/cocoon"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
